# Languages at the start of the list are preferred over the ones that come after
# Possible values: "VASTFR", "VCN", "VF", "VJ", "VKR", "VQC", "VOSTFR"
prefer_languages = ["VF", "VOSTFR"]

# Where to put the downloads (an additional folder is created for every series)
download_path = "~/Downloads/Anime-Sama"

# If it downloads or plays the selected episodes
download = true
show_players = false
max_retry_time = 1024

# See https://github.com/yt-dlp/yt-dlp#format-selection
# For exemple, if you want the lowest size, put "+size,+br,+res,+fps" in format_sort
format = ""
format_sort = ""

# What application to use to play
internal_player_command = "mpv"

# url of anime-sama (You shouldn't touch that)
url = "https://anime-sama.fr/"

[concurrent_downloads]
# how many fragment of a video to download at once
fragment = 3
# how many video to download at once
video = 5
